environment:
  nodejs_version: "8"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run -s lint
  - npm run custom-build

build: off